export const BOOK_LIST_REQUEST = "BOOK_LIST_REQUEST";
export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";
export const BOOK_LIST_FAIL = "BOOK_LIST_FAIL";
export const BOOK_ADD_ITEM = "BOOK_ADD_ITEM";
export const BOOK_REMOVE_ITEM = "BOOK_REMOVE_ITEM";
